server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.183.130:3306/seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 192.168.183.130:8848
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 192.168.183.130:8848
      context-path: /nacos
      #      namespace: ""
      group: SEATA_GROUP
      cluster: chengdu
      application: seata-server # tc服务在nacos中的服务名称
      username: nacos
      password: nacos

  config:
    type: nacos
    nacos:
      server-addr: 192.168.183.130:8848
      context-path: /nacos
      #      namespace: ""
      group: SEATA_GROUP
      data-id: seata.properties
      username: nacos
      password: nacos

  tx-service-group: my-group # 事务组，根据这个获取tc服务的cluster名称
  #  tx-service-group: seata-demo # 事务组，根据这个获取tc服务的cluster名称
  #  service:
  #    vgroup-mapping: # 事务组与TC服务cluster的映射关系
  #      seata-demo: SH
  #  data-source-proxy-mode: XA
  data-source-proxy-mode: AT

  client:
    tm:
      default-global-transaction-timeout: 600000